### ISSUE TITLE
Dúvida! 

### ISSUE THREAD

**Issue by leonhatori** [rubynostrilhos/forum#1]
Consegui configurar minha aplicação (que basicamente é um job board) para ter duas páginas. A primeira disponibiliza uma campo com todas as vagas, e a segunda é um redirecionamento do link "Adicionar nova vaga", onde o usuário cadastra as vagas e elas vão para a página principal (do index). 

Porém, ao realizar testes, cadastrei duas vagas, que não consigo mais apagar. 
Tenho que passar esse comando de apagar nas rotas e no controller?

Como faço isso? haha
Peguei um template pra aprender, e estou me virando, por isso desconsidere se a pergunta for idiota.

**Comment by lucasprag** [comment]
Legal, preciso saber de algumas coisas:
- o código das suas rotas
- o código do seu botão de deletar
- o código da action do controller que vai deletar a vaga

Vou postar aqui como o código deveria ser em breve, e não se preocupe, não existem perguntas idiotas, tudo mundo está aprendendo. O legal é sempre ajudar os outros pq é assim que a gente aprende mais. =)

**Comment by lucasprag** [comment]
Vamos la, vamos conferir passo a passo:

Esse é o arquivo `config/routes.rb`, a parte importante aqui é `resources :jobs`:

```ruby
Rails.application.routes.draw do
  resources :jobs
end
```

Esse é o botão que deleta a vaga (job):
```erb
<%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %>
```

Essa é a action do controller que vai deletar (`app/controllers/job_controller.rb`)

```ruby
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
```

Perceba também que no controller tem outras partes importantes que são o método privado `set_job`:

```ruby
  private
    def set_job
      @job = Job.find(params[:id])
    end
```

e o método que roda antes das actions listadas:
```
  before_action :set_job, only: [:show, :edit, :update, :destroy]
```

Eu criei um [projeto](https://github.com/rubynostrilhos/job_board) bem simples só para mostrar tudo funcionando, você pode ver os comandos que eu usei pra criar ele pelos comentários dos [commits](https://github.com/rubynostrilhos/job_board/commits/master).

**Comment by lucasprag** [comment]
A sua pergunta é muito legal porque me dá idéias sobre o que escrever no blog, vou escrever uns posts com tutoriais de como criar esses projetos explicando passo-a-passo.

Então obrigado =)

**Comment by lucasprag** [comment]
@leonhatori Por favor depois me avisa se você conseguiu =)

**Comment by lucasprag** [comment]
Alguma novidade @leonhatori ?

**Comment by leonhatori** [comment]
cara, desculpa a demora. não recebi a notificação da sua resposta aqui! vou dar uma lida nas suas respostas e colocar o código aqui!

**Comment by leonhatori** [comment]
não deu certo. posso zipar e te mandar o arquivo por aqui? abraços

**Comment by lucasprag** [comment]
Claro, me manda no just.lucasoliveira@gmail.com por favor.

**Comment by leonhatori** [comment]
fala meu caro! obrigado!

coloquei os arquivos no we transfer - https://we.tl/D6GjHRir3f

**Comment by lucasprag** [comment]
Legal, pelo que eu vi o erro está no seu botão Destroy

Você pode mudar o seu botão de:

```erb
<%= link_to 'Delete', jobs_path(jobs), method: :delete, data: { confirm: 'Are you sure?' } %> 
```

para:

```erb
 <%= link_to 'Delete', job, method: :delete, data: { confirm: 'Are you sure?' } %> 
```

Veja que o que mudou foi a URL do link, de `jobs_path(jobs)` para `job`. Isso porque o rails sabe identificar que `job` é um model e ele vai mandar para a URL `show` (`posts/:id`) dele que quando você usa o `method: :delete` o rails deleta o model em questão.

Seria a mesma coisa que usar `job_path(job)` (no singular).

Veja se funciona @leonhatori =)

**Comment by leonhatori** [comment]
entendi! mas ainda tá dando erro cara. parece ser algo com o index mesmo. 
![erro heroku](https://user-images.githubusercontent.com/12173377/34307968-f55d3f20-e731-11e7-98a1-88fd4b613506.png)

**Comment by lucasprag** [comment]
Legal, esse erro ai é diferente. Ele diz que o model `Job` não tem o método `description`.
Então você pode apenas remover essa linha do seu template:

```erb
<%= jobs.description %>
```

Por favor me avise se funcionou depois, obrigado =)

**Comment by leonhatori** [comment]
estranho! não tem nada com esses termos no meu template, hahaha. 
![description](https://user-images.githubusercontent.com/12173377/34310092-9d909b92-e73c-11e7-8110-4aef352114c8.png)

**Comment by lucasprag** [comment]
É no arquivo `lawtechbr/app/views/jobs/index.html.erb` linha 18 @leonhatori =)

Perdão pela demora no feriado =)

**Comment by leonhatori** [comment]
![logs](https://user-images.githubusercontent.com/12173377/34394075-28b730fa-eb3e-11e7-88ef-0f9c10289650.png)

Tranquilo! Continua dando erro aqui...  :(

**Comment by lucasprag** [comment]
Legal, vamos comparar o seu código com o código do [exemplo](https://github.com/rubynostrilhos/job_board/blob/master/app/views/jobs/index.html.erb) que eu te dei:

Tenha em mente que o erro no seu log é `Undefined local variable or method job`

Arquivo: `app/views/jobs/index.html.erb`

**seu código***
```erb
<% @jobs.each do |jobs| %>

    <%= jobs.title %> :

    <%= jobs.description %>

    <%= link_to 'Edit', edit_jobs_path(jobs) %>
    <%= link_to 'Show', jobs %>
    <%= link_to 'Delete', jobs_path(jobs), method: :delete, data: { confirm: 'Are you sure?' } %> 
    <br/>

<% end %>
```

**meu código**

```erb
    <% @jobs.each do |job| %>
      <tr>
        <td><%= job.title %></td>
        <td><%= job.description %></td>
        <td><%= link_to 'Show', job %></td>
        <td><%= link_to 'Edit', edit_job_path(job) %></td>
        <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
```

Veja que no meu loop eu defino a variável `job`, no seu você define a variável `jobs` dentro do bloco
```ruby
@jobs.each do |jobs|
# vs
@jobs.each do |job|
```

Então você precisa deixar o seu código assim para deixar o nome da variável correto (rubistas tem a convenção de que se uma variável está no plural, então deve ser uma lista, e se está no singular, então deve ser o objeto em questão):

```erb
<% @jobs.each do |job| %>
    <%= job.title %> :
    <%= link_to 'Edit', edit_job_path(job) %>
    <%= link_to 'Show', job %>
    <%= link_to 'Delete', job, method: :delete, data: { confirm: 'Are you sure?' } %>
    <br/>
<% end %>
```

(inclusive arrumei os paths, exemplo `edit_jobs_path(jobs)` para `edit_job_path(job)`)

Veja se ele funciona agora e me diz o resultado.

**Dica:** Fique atendo ao que o log te diz, o log é a nossa maior fonte de informação no caso de erros. Também sugiro você baixar o projeto de [exemplo](https://github.com/rubynostrilhos/job_board) e dar uma olhada como [eu fiz](https://github.com/rubynostrilhos/job_board/commits/master).

Obrigado =)

**Comment by lucasprag** [comment]
Conseguiu @leonhatori ?

**Comment by leonhatori** [comment]
Cara, não consegui! Alias, estou desistindo de usar Ruby nesse projeto. Infelizmente está ficando muito complexo. Mas super agradeço a ajuda!

**Comment by lucasprag** [comment]
Que pena cara =/

Acho que vc precisa reduzir o escopo do que você está fazendo, talvez não subir para o heroku enquanto não estiver pronto por exemplo.

Veja que eu fiz o CRUD dos jobs com apenas um comando:

```bash
# para criar um projeto rails
$ rails new job_board

# para criar o CRUD de Jobs
$ bin/rails g scaffold Job title:string description:text

# sobe um servidor com a app em http://localhost:3000
$ rails server

# visite http://localhost:3000/jobs
```

Acho que seria legal vc fazer um pequeno curso online ou talvez participar de um grupo de estudos como o [ruby-study-group](https://github.com/training-center/ruby-study-group)

Continua tentando que você consegue o/

Abraço o/
